[profile.default]
optimizer_runs = 100000
src = 'contracts'
fs_permissions = [{ access = "read", path = "./deployments/"}]

[rpc_endpoints]
goerli = "${RPC_URL_GOERLI}"
mainnet = "${RPC_URL_MAINNET}"
poly_zk_test = "https://rpc.public.zkevm-test.net"

[etherscan]
goerli = {key = "${ETHERSCAN_API_KEY}", url = "https://api-goerli.etherscan.io/api"}
mainnet = {key = "${ETHERSCAN_API_KEY}"}